import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "IEEE 754 Converter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          inter.variable,
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          //disableTransitionOnChange
        >
          {children}
          <div className="flex flex-col sm:flex-row justify-between bg-gray-black text-white p-2">
            <div className="footer flex flex-col">
              <p className="font-semibold">tEST</p>
              <p className="text-sm mt-2">tEST</p>
            </div>
            <a
              target="_blank"
              className="text-sm mt-4 hover:underline items-end"
              href="https://github.com/"
            >
              GitHub Repository
            </a>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
